modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/Mrthomas20121/tfctweaker/issues"

[[mods]]
modId="tfctweaker"
version="0.0.3"
displayName="TFCTweaker"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tfctweaker"
authors="Mrthomas20121"
description='''
Add crafttweaker support to TFC.
'''

[[dependencies.tfctweaker]]
	modId = "tfc"
    mandatory = true
    versionRange = "[2.0.15,)"
    ordering = "NONE"
    side = "BOTH"